# Generated by Django 2.1.7 on 2019-03-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField()),
                ("city", models.CharField(max_length=1100)),
                ("time", models.DateTimeField()),
            ],
        )
    ]
